- shard.lock
- src/core/compilation.cr
- src/core/module_manager.cr
1. driver recompiled after commit change
1. associated modules (if any) are stopped
1. stale driver binary (if any) deleted
1. driver's modules restarted on the freshly compiled binary
I'm particularly aware of [allocating an array of Modules](https://github.com/PlaceOS/core/blob/reload-modules/src/core/compilation.cr#L85). Is it really necessary to stop the modules before deleting the binary?
> improvement(resource:compilation): start modules on freshly compiled drivers

- src/app.cr
- src/config.cr
`Log` was bound to `core` while the codebase was using `Log.for(self)` which produces the log namespace `place_os.core`
> fix(log): bind to correct log namespace

- Dockerfile
Provides support for building both `edge` and `core` outputs from single `Dockerfile`.
General neaten up the docker builds and adds support for specifying the build target. This works with the vanilla docker build, as well as buildkit. When using buildkit unused stages will be automatically skipped.
> Support `TARGET` build-arg in Dockerfile

- shard.lock
- src/placeos-core/client.cr
- src/placeos-core/process_manager/edge.cr
- src/placeos-edge/client.cr
- src/placeos-edge/protocol.cr
- src/placeos-edge/transport.cr
Skips an allocation into an intermediate `IO::Memory` when passing a driver binary to an edge node
> improvement: reduce allocation when sending/receiving driver binaries

- Dockerfile
- shard.lock
- shard.override.yml
- shard.yml
- src/config.cr
- src/controllers/command.cr
- src/placeos-core/client.cr
- src/placeos-core/compilation.cr
- src/placeos-core/module_manager.cr
- src/placeos-core/process_manager.cr
- src/placeos-core/process_manager/edge.cr
- src/placeos-core/process_manager/local.cr
- src/placeos-edge/client.cr
- src/placeos-edge/protocol.cr
- src/placeos-edge/transport.cr
Resolves an issue where modules that were reloaded onto a new driver binary would not propagate any existing debug listeners to the module on the new driver.
Closes PlaceOS/rest-api/issues/94
> fix: preserve debug connections when reloading modules

- shard.lock
- shard.yml
- spec/processes/edge_spec.cr
- spec/processes/local_spec.cr
- src/constants.cr
- src/controllers/chaos.cr
- src/core-app.cr
- src/ext.cr
- src/placeos-core.cr
- src/placeos-core/compilation.cr
- src/placeos-core/module_manager.cr
- src/placeos-core/process_manager.cr
- src/placeos-core/process_manager/edge.cr
- src/placeos-core/process_manager/local.cr
- src/placeos-edge.cr
- Added a lock around the stabilizing method in `module_manager.cr` to ensure that only a single module load occurs
- Refactored all internal references to use the driver binary name, and only use the path when starting the driver protocol manager
> refactor: use driver key internally, lock stabilisation

- Dockerfile
- spec/controllers/drivers_spec.cr
Ensures `yaml-static` is available to the build layer.
Minor neaten up to remove double pull of package index.
> fix: alpine build

- Dockerfile
Drops variants used for dynamic linking. This is used by drivers which [now build statically](https://github.com/PlaceOS/compiler/pull/16).
> fix: drop excess libssh2 libs

- shard.lock
- shard.yml
- spec/cloning_spec.cr
- spec/controllers/command_spec.cr
- spec/controllers/drivers_spec.cr
- spec/controllers/status_spec.cr
- spec/helper.cr
- spec/mappings/control_system_modules_spec.cr
- spec/module_manager_spec.cr
- spec/resource_manager_spec.cr
- src/placeos-core/mappings/control_system_modules.cr
- src/placeos-core/settings_update.cr
- `ControlSystemModules`: if errors raised when updating modules, the mappings process is unaffected.
- `SettingsUpdates`: if errors raised when updating a module onto new settings, the rest of the module reloads are unaffected
- DRY out a few mocks used across the test suite 
- Stop using a shared global `ResourceManager` instance in specs
Fixes #92
> test: robust module mapping updates

- Dockerfile
- Dockerfile.test
Bumps crystal to v1.1.1
This enables use of the [crunits library](https://github.com/spider-gazelle/crunits) in drivers
> build: bump to crystal 1.1.1

- shard.yml
Updates minimum supported placeos-models version.
v5.10.0 was already locked, but bumping min spec for safety.
> chore: placeos-models ~>5.9

- shard.lock
- shard.override.yml
- shard.yml
Includes an update to ensure changefeeds _always_ reconnect.
Writes would fail and not trigger a reconnect, leaving changefeeds waiting on IO.
> fix: reconnection

- Dockerfile.test
- docker-compose.yml
Support `CRYSTAL_VERSION` build argument when building the image
> ci: use standard CRYSTAL_VERSION

- .github/workflows/ci.yml
- Dockerfile.test
- scripts/entrypoint.sh
- spec/api/command_spec.cr
- spec/api/drivers_spec.cr
- spec/api/root_spec.cr
- spec/api/status_spec.cr
- spec/mappings/control_system_modules_spec.cr
- spec/mappings/module_names_spec.cr
- spec/module_manager_spec.cr
- spec/placeos-edge/client_spec.cr
- spec/processes/edge_spec.cr
- spec/processes/local_spec.cr
- test
This is unfortunately necessary because we're hitting the Github Action Runners memory limit.
This change should be considered temporary until the spec's memory usage can be minimised.
> ci: split tests

- docker-compose.yml
- shard.lock
- src/api/root.cr
- src/core-app.cr
- src/placeos-core.cr
- src/placeos-core/healthcheck.cr
- Updates `crystal-etcd` to fix an issue with etcd > `3.3`
- Adds a check at startup that all upstream services are available
> build: update `crystal-etcd`

- src/api/command.cr
found as part of an update to core-client
> fix(api): add error codes coming from RemoteExceptions

- src/placeos-core/process_manager/common.cr
was catching all exceptions however this one is expected and handled upstream in the controller
> fix(process_manager/common): should propagate RemoteExceptions

- spec/module_manager_spec.cr
Sleep after starting the module manager to mirror real world timing & ensure reliable spec
**Applicable issues**
Closes #168
> test(module_manager): sleep to stabilise spec

- shard.lock
- src/placeos-core/process_manager/common.cr
- src/placeos-edge/client.cr
Update to `placeos-compiler` to turn the check into a lazy one.
**Benefits**
Edge app can start now.
**Possible drawbacks**
May delay the failure of a core without crystal in the environment, but realistically this will never happen
> fix(edge): resolve `crystal binary in the environment` error

- spec/placeos-edge/client_spec.cr
- src/placeos-edge/client.cr
- src/placeos-edge/constants.cr
Ensure the edge client is using the right param for api-key authentication and that parts of the api key are the correct length.
**Benefits**
Edge client can successfully auth a ws connection against the edge control endpoint.
**Possible drawbacks**
ID or hash length could change in the api key making validation fail.
> fix(edge): use correct api-key param and update key validation 

- src/placeos-core/mappings/control_system_modules.cr
- src/placeos-core/module_manager.cr
related to comments in #212 but not a fix for that issue
This pull does two things:
1. ensures the module state is updated with the latest version of the control system module
2. updates module state on cores that are not managing the system module mappings / lookup tables
> fix(control_system_modules): update system references in modules

- shard.lock
- shard.yml
- spec/api/command_spec.cr
- spec/processes/local_spec.cr
- src/constants.cr
- src/placeos-core/module_manager.cr
- src/placeos-core/process_check.cr
- src/placeos-core/process_manager/common.cr
Checks that drivers are responsive to comms periodically, and if they're not, it kills them and reloads all assigned modules.
Comes with two new environment variables...
- `PLACE_CORE_PROCESS_CHECK_PERIOD`: How often to check for dead processes
- `PLACE_CORE_PROCESS_COMMS_TIMEOUT`: How long to wait before assuming the driver's comms are borked
> feat(module_manager): periodically check that processes are alive

- src/placeos-core/process_check.cr
- Gets rid of a cast introduced by timeout shard
- Ignore empty module state
> fix: ignore empty module

- shard.lock
- shard.override.yml
- spec/mappings/driver_module_names_spec.cr
- src/placeos-core/cloning.cr
- src/placeos-core/mappings/control_system_modules.cr
- src/placeos-core/mappings/driver_module_names.cr
- src/placeos-core/mappings/module_names.cr
- src/placeos-core/resource_manager.cr
- src/placeos-core/settings_update.cr
Updates the `name` of modules when `module_name` of a driver changes. 
Modules with a `custom_name` won't have their mappings effected, however their `name` field will still update. 
**Applicable issues**
- Closes #212
> fix: handle driver `module_name` changes in module mappings

- .gitignore
- src/placeos-edge/client.cr
- src/placeos-edge/transport.cr
Retriable lib is unreliable, moving to simple_retry lib
> fix(edge/transport): ensure reconnect is not missed

- src/placeos-core/process_manager/local.cr
previous to this, edge modules were only accessible via the frontend (no cross module comms were possible)
> fix(process_manager/local): add edge node awareness

- shard.lock
- spec/processes/edge_spec.cr
- spec/processes/local_spec.cr
- src/placeos-core/healthcheck.cr
- src/placeos-core/module_manager.cr
- src/placeos-core/process_manager/common.cr
- src/placeos-core/process_manager/edge.cr
- src/placeos-core/process_manager/local.cr
- src/placeos-core/resource_manager.cr
- src/placeos-edge/client.cr
such as slow redis response time or partial outage
> feat: improve cluster stabilisation under adverse conditions
