PlaceOS/core

- shard.lock
- spec/controllers/drivers_spec.cr
- spec/controllers/status_spec.cr
- spec/helper.cr
- src/core/compilation.cr
- src/core/module_manager.cr
Reloads modules if they're already compiled.
Fixes #6
> fix(resource:compilation): launch modules if binary already present

- shard.lock
- spec/cloning_spec.cr
- spec/controllers/command_spec.cr
- spec/helper.cr
- spec/mappings/control_system_modules_spec.cr
- spec/mappings/module_names_spec.cr
- spec/settings_update_spec.cr
- src/core/cloning.cr
- src/core/resource_manager.cr
- src/core/settings_update.cr
This PR implements a `Resource` for `Model::Settings` that listens for a change on the `Settings` table and reloads any dependent modules upon changes.
It also includes some small fixes including recursively deleting a repository on destroy.
Fixes #7
> feat(settings_update)

- src/controllers/drivers.cr
replaces logic which compiled a driver for each details request
> perf(controller:details): cache details requests

- src/core/compilation.cr
> feat(resource:compilation): react to forced recompile data events

- shard.yml
- src/core/client.cr
Yields a core client connection to a block and closes the connection after the block returns.
> improvement(client): one-shot client via `PlaceOS::Core::Client.client`

- shard.yml
- src/placeos-core/module_manager.cr
Modules will restart if ip, port, tls, udp, makebreak, or uri change.
Resolves Placeos/driver/issues/14
> improvement(module_manager): conditional module restart

- shard.lock
- shard.yml
- src/placeos-core/module_manager.cr
- REFACTOR: change `ModuleManager` into a subclass of `Resource` for better error handling.
- FIX: added a lock when accessing the `driver_proc_managers` in `#loaded_modules`
> fix(module_manager): convert to a Resource

- shard.lock
- shard.yml
- src/config.cr
- src/constants.cr
- src/controllers/drivers.cr
Aim is to move most of the references to `ENV` in the config file
> feat: add secrets and clean up config

- spec/controllers/command_spec.cr
- src/controllers/command.cr
this has the potential to break / fix various components - but probably worth fixing before we do the first release
> fix(command controller): don't double serialize JSON

- shard.lock
to resolve potential memory leak
> fix: update tasker

- shard.lock
- shard.yml
- src/placeos-core/cloning.cr
- src/placeos-core/compilation.cr
- src/placeos-core/mappings/control_system_modules.cr
- src/placeos-core/mappings/module_names.cr
- src/placeos-core/module_manager.cr
- src/placeos-core/settings_update.cr
not sure what the error is @caspiano
> WIP: update placeos resource

- shard.yml
- src/controllers/drivers.cr
- src/placeos-core/cloning.cr
- src/placeos-core/compilation.cr
- src/placeos-core/module_manager.cr
- src/placeos-core/resource.cr
- src/placeos-core/settings_update.cr
- Refactor to use crystal lazy getters
- Remove reimport of `PlaceOS::Resource`
> refactor: lazy getters

- shard.lock
- shard.yml
- src/constants.cr
- src/placeos-core/compilation.cr
- src/placeos-core/mappings/control_system_modules.cr
- src/placeos-core/module_manager.cr
- src/placeos-core/settings_update.cr
Update any logic `Module`s directly associated with a `ControlSystem` on update/create.
> fix: update system logic modules

- shard.lock
- shard.yml
- spec/helper.cr
- src/app.cr
> feat: add environment variable list behind `-e/--env`

- Dockerfile
Add explicit docker volume to the core container
> build(Dockerfile): add volume

- .travis.yml
- Dockerfile
Add the container user as the owner of the driver binary volume
> build(Dockerfile): set permissions on driver volume

- docker-compose.yml
- src/app.cr
- src/placeos-core.cr
to fix health checks when booting
> Quick start

- src/controllers/root.cr
- src/placeos-core/resource_manager.cr
adds `/api/core/v1/ready` for a readiness probe
> improvement(controller:root): readiness probe

- .github/workflows/test.yml
- .travis.yml
- Dockerfile
- Dockerfile.test
- shard.lock
- shard.override.yml
- shard.yml
- spec/helper.cr
- src/placeos-core/process_manager.cr
- src/placeos-edge/client.cr
- src/placeos-edge/protocol.cr
Bump shards and crystal to v0.36.0
> build: use crystal v0.36.0

- shard.lock
- shard.yml
- spec/helper.cr
- src/config.cr
- src/core-app.cr
- src/placeos-core/module_manager.cr
- src/placeos-core/process_manager.cr
- src/placeos-core/process_manager/edge.cr
- src/placeos-core/process_manager/local.cr
- Add `on_system_model` callback for `ControlSystem` lookups from logic modules
- Add [place-labs/log-backend](https://github.com/place-labs/log-backend)
> feat(process_manager): add system_model callback

- Dockerfile.test
- shard.lock
- shard.yml
- src/placeos-core/module_manager.cr
Reuses the batching method from [place-labs/resource](github.com/place-labs/resource) to load modules during the stabilisation event in parallel
> perf: load modules in parallel when stabilizing

- shard.lock
- shard.yml
- src/placeos-core/compilation.cr
Adds compilation to the driver model if it fails to compile.
> feat(resource:compilation): add failed compilation output to the driver

- Dockerfile
- Dockerfile.test
- shard.lock
- shard.yml
> chore: bump to crystal v1.0.0

- shard.lock
- shard.yml
- src/controllers/root.cr
Healthcheck against the connection status of rethinkdb, redis, and etcd.
Closes #74
> feat(controller:root): better healthcheck

- shard.lock
Bumps etcd and hound-dog libraries.
> chore(shard.lock): bump etcd

- shard.lock
- shard.yml
- src/controllers/drivers.cr
- src/controllers/root.cr
- src/placeos-core/cloning.cr
- src/placeos-core/compilation.cr
- src/placeos-core/mappings/control_system_modules.cr
- src/placeos-core/mappings/module_names.cr
- src/placeos-core/settings_update.cr
Update in [`PlaceOS/driver`](https://github.com/PlaceOS/driver/pull/62) resolves a reentrant lock acquisition error.
Fixes #87
> fix: resolve deadlock when driver with debugged modules is updated

- shard.lock
- shard.yml
- src/config.cr
- src/core-app.cr
Integrates the signal handler from [`PlaceOS/log-backend`](https://github.com/place-labs/log-backend/pull/5)
> feat: add verbose signalling

- shard.lock
- shard.yml
- src/controllers/command.cr
- src/placeos-core/cloning.cr
Bump `placeos-models` to 4.15.5
Includes some minor style adjustments.
> chore: bump models

- docker-compose.yml
- shard.lock
- shard.override.yml
- shard.yml
> chore: bump clustering

- shard.lock
- shard.override.yml
- shard.yml
- spec/cloning_spec.cr
- spec/compilation_spec.cr
- spec/helper.cr
- spec/mappings/module_names_spec.cr
- spec/resource_spec.cr
- spec/settings_update_spec.cr
- src/placeos-core/cloning.cr
- src/placeos-core/mappings/control_system_modules.cr
- src/placeos-core/mappings/module_names.cr
Adds support for branch switching on `Driver` repositories. 
Adds some minor tests for exceptional cases in `ModuleNames` and `SettingsUpdates`.
> feat: branch switching

- src/config.cr
- src/logging.cr
Moves logging config out from `/src/config.cr` to `/src/logging.cr`
> refactor(config): extract logging to logging.cr

- shard.lock
- shard.yml
- spec/controllers/drivers_spec.cr
- spec/controllers/status_spec.cr
- spec/module_manager_spec.cr
- spec/processes/edge_spec.cr
- spec/processes/local_spec.cr
- src/controllers/drivers.cr
- src/placeos-core/client.cr
- src/placeos-core/mappings/module_names.cr
- src/placeos-core/process_manager.cr
- src/placeos-core/process_manager/edge.cr
- src/placeos-core/process_manager/local.cr
- src/placeos-edge/protocol.cr
Add branch listing under `GET .../drivers/:repository/branches`, returning `Array(String)`, or a 404 if not found.
> feat: list branches

- shard.lock
- shard.yml
- src/logging.cr
> fix(logging): set progname

- .github/workflows/ci.yml
- .github/workflows/test.yml
- .travis.yml
- Dockerfile
- Dockerfile.test
- docker-compose.yml
- shard.lock
- test
Adds a matrix of crystal versions to the specs.
> ci: allow varying crystal version

- shard.lock
- shard.yml
Bump some shards, specifically `rethinkdb-orm`
> chore: bump shards

- shard.yml
- src/placeos-core/client.cr
> fix(core client): ensure body has completely downloaded

- shard.yml
- src/placeos-core/client.cr
versus using the callback streaming method
> fix(core client): wait for response to complete

- .github/workflows/ci.yml
- shard.lock
- shard.yml
- src/placeos-core/cloning.cr
> fix(resource:cloning): decrypt password on use

- src/placeos-core/process_manager/local.cr
Minor refactor that's been sitting stagnant on a branch.
> refactor(module_manager): helper to fetch manager

- CHANGELOG.md
- shard.lock
- shard.yml
- spec/api/drivers_spec.cr
Closes #127 
See https://github.com/PlaceOS/compiler/issues/39 for further information
> fix: allow updates to username and password

- shard.lock
- shard.yml
- src/api/drivers.cr
Account for branches when listing commits
Related https://github.com/PlaceOS/compiler/issues/41
> fix(api:drivers): account for branch in commit listing

- .github/workflows/ci.yml
- shard.lock
- src/placeos-core/process_manager/edge.cr
Adds support for proxied redis `PUBLISH` events from edge nodes.
> fix(edge): handle proxied PUBLISH events

- .github/workflows/ci.yml
- shard.lock
- shard.yml
- spec/api/drivers_spec.cr
- spec/processes/edge_spec.cr
- spec/processes/local_spec.cr
- src/api/application.cr
- src/api/command.cr
- src/placeos-core/process_manager.cr
- src/placeos-core/process_manager/edge.cr
- src/placeos-core/process_manager/local.cr
- src/placeos-edge/client.cr
- src/placeos-edge/protocol.cr
Closes https://github.com/PlaceOS/core/issues/126
> feat(api/command): propagate `user_id`

- Dockerfile
- shard.lock
> chore: bump to placeos-driver 5.9.19

- shard.lock
- spec/helper.cr
- spec/processes/edge_spec.cr
- spec/processes/local_spec.cr
- src/placeos-core/error.cr
- src/placeos-edge/client.cr
- src/placeos-edge/constants.cr
Component of https://github.com/PlaceOS/rest-api/issues/174
> refactor(edge/client): update secret, remove `edge_id`

- .github/workflows/ci.yml
- spec/helper.cr
- src/api/command.cr
- src/placeos-core/error.cr
- src/placeos-core/process_manager/local.cr
Extra information during method executes on a module that is not found or stopped
**Benefits**
Easier debugging, potentially enabling simpler recovery through further work.
> fix: better module stopped errors

- .github/workflows/todos.yml
- spec/processes/edge_spec.cr
- src/placeos-core/compilation.cr
- src/placeos-core/module_manager.cr
- src/placeos-core/process_manager/edge.cr
- src/placeos-core/process_manager/local.cr
- src/placeos-edge/protocol.cr
- Minor changes to specs and comments in codebase
- Adds `.github/workflows/todos.yml`
**Benefits**
- Automatic tracking of TODOs in codebase
**Possible drawbacks**
Potential bugs in the action used to maintain the TODO issues
> ci: reword TODOS in code, add `todos.yml`

- src/placeos-core.cr
This spawn was introduced in #59 to solve an issue with an instance being unhealthy during compilation on boot.
However it seems this spawn is surplus to that goal and might introduce race conditions
> fix: possible race condition in spawn

- .github/workflows/ci.yml
- spec/mappings/control_system_modules_spec.cr
- src/placeos-core/mappings/control_system_modules.cr
Also resolves and issue in specs
> fix(control_system_modules): ensure correct totals when refreshing

- shard.lock
- src/placeos-core/process_check.cr
[Original PR that introduced these changes are here](https://github.com/PlaceOS/core/pull/225/)
> fix(process_check): fix a race condition

- shard.lock
- shard.yml
- src/constants.cr
- src/placeos-core/process_check.cr
Simplifies the behaviour of timeouts
> refactor: use Tasker instead of Timeout shard

- .gitignore
- Dockerfile
- OPENAPI_DOC.yml
- shard.lock
- shard.yml
- spec/api/command_spec.cr
- spec/api/drivers_spec.cr
- spec/api/root_spec.cr
- spec/api/status_spec.cr
- spec/helper.cr
- src/api/application.cr
- src/api/chaos.cr
- src/api/command.cr
- src/api/drivers.cr
- src/api/edge.cr
- src/api/root.cr
- src/api/status.cr
- src/constants.cr
- src/core-app.cr
> feat: update action controller and support ARM64

- Dockerfile
- shard.lock
> feat(Dockerfile): revert static build

- OPENAPI_DOC.yml
- shard.lock
- src/api/status.cr
for better OpenAPI descriptions
> chore(api/status): ensure responses are documented

- src/placeos-core/process_manager/edge.cr
- src/placeos-edge/client.cr
- src/placeos-edge/transport.cr
ensure modules are running after the registration process is complete
> fix(manager/edge): start modules after registration

- src/placeos-core/process_manager/edge.cr
- src/placeos-edge/client.cr
- src/placeos-edge/protocol.cr
reduces the chance of a race condition
> feat(edge/protocol): start modules as part of the handshake

- .github/workflows/ci.yml
- Dockerfile
- docker-compose.yml
- shard.lock
- test
using placeos/crystal:latest base image
> chore: bump deps and update dockerfile

- shard.lock
- src/placeos-edge/client.cr
- src/placeos-edge/protocol.cr
- src/placeos-edge/server.cr
- src/placeos-edge/transport.cr
ensures driver load is eventually consistent, previously failures in core that might be resolved post startup could effect modules running on edge
> feat(edge): improve driver launch reliability

- src/placeos-edge/transport.cr
> fix(edge/transport): restart service after a period of downtime

- src/placeos-core/process_manager/common.cr
IPC should not lock up other operations
This would have also prevented the dead driver detection from working and restarting the driver
> fix(process_manager): don't lock managers when querying

- shard.lock
- src/placeos-core/process_check.cr
- src/placeos-core/process_manager/common.cr
improve locking and ensure consistent state
> fix(process_check): ensure consistent state after recovery

- shard.lock
- src/placeos-core/process_check.cr
relies on updated process management code
> fix(process_check): kill unresponsive processes cleanly
